"""change to agent  table

Revision ID: 757b211643ae
Revises: 0b1e8889a025
Create Date: 2024-07-31 14:10:53.112240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757b211643ae'
down_revision = '0b1e8889a025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_agent_user', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
