"""remove room column

Revision ID: c1bef1f62941
Revises: 1f1fdc18ff76
Create Date: 2024-08-06 15:11:39.755029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bef1f62941'
down_revision = '1f1fdc18ff76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('rooms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rooms', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
