"""empty message

Revision ID: f8dd17b53bc2
Revises: f88286dbcb37
Create Date: 2024-08-13 22:50:50.399967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8dd17b53bc2'
down_revision = 'f88286dbcb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payment', schema=None) as batch_op:
        batch_op.drop_column('installment_amount')

    # ### end Alembic commands ###
